# Generated by Django 3.2.25 on 2025-08-22 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0004_merge_0002_load_categories_0003_load_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location_name', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('recommendation_score', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='User.category')),
            ],
        ),
    ]
