# Generated by Django 3.2.25 on 2025-08-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localevent',
            name='api_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='localevent',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='localevent',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='localevent',
            name='org_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='localevent',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='localevent',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localevent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localevent',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='localevent',
            name='recommendation_score',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='localevent',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
