# Generated by Django 3.2.25 on 2025-08-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_events', '0002_auto_20250825_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_nm', models.CharField(max_length=100)),
                ('area_cd', models.CharField(max_length=100, unique=True)),
                ('rsb_sh_payment_cnt', models.IntegerField(default=0)),
                ('cmrcl_10_rate', models.FloatField(default=0.0)),
                ('cmrcl_20_rate', models.FloatField(default=0.0)),
                ('cmrcl_30_rate', models.FloatField(default=0.0)),
                ('cmrcl_40_rate', models.FloatField(default=0.0)),
                ('cmrcl_50_rate', models.FloatField(default=0.0)),
                ('cmrcl_60_rate', models.FloatField(default=0.0)),
                ('live_cmrcl_stts', models.CharField(blank=True, max_length=100, null=True)),
                ('area_cmrcl_lvl', models.CharField(blank=True, max_length=100, null=True)),
                ('area_sh_payment_cnt', models.IntegerField(default=0)),
                ('rsb_lrg_ctgr', models.CharField(blank=True, max_length=100, null=True)),
                ('rsb_mid_ctgr', models.CharField(blank=True, max_length=100, null=True)),
                ('rsb_payment_lvl', models.CharField(blank=True, max_length=100, null=True)),
                ('rsb_mct_time', models.CharField(blank=True, max_length=100, null=True)),
                ('cmrcl_male_rate', models.FloatField(default=0.0)),
                ('cmrcl_female_rate', models.FloatField(default=0.0)),
                ('cmrcl_personal_rate', models.FloatField(default=0.0)),
                ('cmrcl_time', models.CharField(blank=True, max_length=100, null=True)),
                ('area_sh_payment_amt_min', models.IntegerField(default=0)),
                ('area_sh_payment_amt_max', models.IntegerField(default=0)),
                ('rsb_sh_payment_amt_min', models.IntegerField(default=0)),
                ('rsb_sh_payment_amt_max', models.IntegerField(default=0)),
                ('cmrcl_corporation_rate', models.FloatField(default=0.0)),
            ],
        ),
    ]
