# Generated by Django 3.2.25 on 2025-08-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_load_categories'),
        ('User', '0003_load_locations'),
    ]

    operations = [
    ]
