# Generated by Django 3.2.25 on 2025-08-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('disaster', '자연재해'), ('accident', '사고'), ('traffic', '교통'), ('safety', '치안'), ('facility', '시설고장'), ('etc', '기타')], max_length=20)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('location_name', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
