# Generated by Django 3.2.25 on 2025-08-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicalert',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
