# Generated by Django 3.2.25 on 2025-08-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_data', '0002_publicalert_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('tel', models.CharField(max_length=50)),
                ('police_office', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
