# Generated by Django 3.2.25 on 2025-08-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_data', '0003_safetyfacility'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_name', models.CharField(max_length=255)),
                ('gu_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='SafetyFacility',
        ),
    ]
