# Generated by Django 3.2.25 on 2025-08-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_data', '0004_auto_20250825_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50, unique=True)),
                ('subjcode', models.CharField(blank=True, max_length=100, null=True)),
                ('fac_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('homepage', models.URLField(blank=True, max_length=500, null=True)),
                ('open_hour', models.CharField(blank=True, max_length=255, null=True)),
                ('entr_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('close_day', models.CharField(blank=True, max_length=255, null=True)),
                ('open_day', models.CharField(blank=True, max_length=255, null=True)),
                ('seat_cnt', models.CharField(blank=True, max_length=100, null=True)),
                ('main_img', models.URLField(blank=True, max_length=500, null=True)),
                ('etc_desc', models.TextField(blank=True, null=True)),
                ('fac_desc', models.TextField(blank=True, null=True)),
                ('entrfree', models.CharField(blank=True, max_length=50, null=True)),
                ('subway', models.CharField(blank=True, max_length=255, null=True)),
                ('busstop', models.CharField(blank=True, max_length=255, null=True)),
                ('airport', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
